/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Changelog = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'changeType' : IDL.Text,
  'description' : IDL.Text,
  'version' : IDL.Text,
  'releaseDate' : IDL.Text,
  'changesList' : IDL.Vec(IDL.Text),
});
export const FAQ = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DownloadStats = IDL.Record({
  'windowsDownloads' : IDL.Nat,
  'macosDownloads' : IDL.Nat,
  'linuxDownloads' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
});
export const MembershipStats = IDL.Record({
  'totalGold' : IDL.Nat,
  'totalSilver' : IDL.Nat,
  'totalPlatinum' : IDL.Nat,
  'totalMembers' : IDL.Nat,
});
export const SavedConfig = IDL.Record({
  'id' : IDL.Nat,
  'os' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'configData' : IDL.Text,
});
export const MembershipTier = IDL.Variant({
  'gold' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
});
export const MembershipRecord = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'tier' : MembershipTier,
  'purchasedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChangelog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'addFAQ' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChangelog' : IDL.Func([IDL.Nat], [], []),
  'deleteConfig' : IDL.Func([IDL.Nat], [], []),
  'deleteFAQ' : IDL.Func([IDL.Nat], [], []),
  'getAllChangelog' : IDL.Func([], [IDL.Vec(Changelog)], ['query']),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDownloadsByOS' : IDL.Func([], [DownloadStats], ['query']),
  'getLatestVersion' : IDL.Func([], [IDL.Text], ['query']),
  'getMembershipStats' : IDL.Func([], [MembershipStats], ['query']),
  'getMyConfigs' : IDL.Func([], [IDL.Vec(SavedConfig)], ['query']),
  'getMyMembership' : IDL.Func([], [IDL.Opt(MembershipRecord)], ['query']),
  'getTotalConfigsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalDownloads' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalMembersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementDownload' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseMembership' : IDL.Func([MembershipTier], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Changelog = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'changeType' : IDL.Text,
    'description' : IDL.Text,
    'version' : IDL.Text,
    'releaseDate' : IDL.Text,
    'changesList' : IDL.Vec(IDL.Text),
  });
  const FAQ = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DownloadStats = IDL.Record({
    'windowsDownloads' : IDL.Nat,
    'macosDownloads' : IDL.Nat,
    'linuxDownloads' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
  });
  const MembershipStats = IDL.Record({
    'totalGold' : IDL.Nat,
    'totalSilver' : IDL.Nat,
    'totalPlatinum' : IDL.Nat,
    'totalMembers' : IDL.Nat,
  });
  const SavedConfig = IDL.Record({
    'id' : IDL.Nat,
    'os' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'configData' : IDL.Text,
  });
  const MembershipTier = IDL.Variant({
    'gold' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
  });
  const MembershipRecord = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'tier' : MembershipTier,
    'purchasedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChangelog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'addFAQ' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChangelog' : IDL.Func([IDL.Nat], [], []),
    'deleteConfig' : IDL.Func([IDL.Nat], [], []),
    'deleteFAQ' : IDL.Func([IDL.Nat], [], []),
    'getAllChangelog' : IDL.Func([], [IDL.Vec(Changelog)], ['query']),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDownloadsByOS' : IDL.Func([], [DownloadStats], ['query']),
    'getLatestVersion' : IDL.Func([], [IDL.Text], ['query']),
    'getMembershipStats' : IDL.Func([], [MembershipStats], ['query']),
    'getMyConfigs' : IDL.Func([], [IDL.Vec(SavedConfig)], ['query']),
    'getMyMembership' : IDL.Func([], [IDL.Opt(MembershipRecord)], ['query']),
    'getTotalConfigsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalDownloads' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalMembersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementDownload' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseMembership' : IDL.Func([MembershipTier], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };