/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Changelog {
  'id' : bigint,
  'title' : string,
  'changeType' : string,
  'description' : string,
  'version' : string,
  'releaseDate' : string,
  'changesList' : Array<string>,
}
export interface ChatbotConfig { 'enabled' : boolean, 'phoneNumber' : string }
export interface DownloadStats {
  'windowsDownloads' : bigint,
  'macosDownloads' : bigint,
  'linuxDownloads' : bigint,
  'totalDownloads' : bigint,
}
export interface FAQ {
  'id' : bigint,
  'question' : string,
  'answer' : string,
  'category' : string,
}
export interface LeaderboardEntry {
  'principal' : Principal,
  'displayName' : string,
  'joinedAt' : bigint,
  'rank' : bigint,
  'tier' : MembershipTier,
  'tokens' : bigint,
  'handle' : string,
}
export interface MembershipRecord {
  'id' : bigint,
  'owner' : Principal,
  'tier' : MembershipTier,
  'purchasedAt' : bigint,
}
export interface MembershipStats {
  'totalGold' : bigint,
  'totalSilver' : bigint,
  'totalPlatinum' : bigint,
  'totalMembers' : bigint,
}
export type MembershipTier = { 'gold' : null } |
  { 'platinum' : null } |
  { 'silver' : null };
export interface SavedConfig {
  'id' : bigint,
  'os' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'configData' : string,
}
export interface TopReward {
  'title' : string,
  'color' : string,
  'rank' : bigint,
  'description' : string,
  'badge' : string,
  'bonusTokens' : bigint,
}
export interface UserProfile { 'bio' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChangelog' : ActorMethod<
    [string, string, string, string, Array<string>, string],
    undefined
  >,
  'addFAQ' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChangelog' : ActorMethod<[bigint], undefined>,
  'deleteChatbotConfig' : ActorMethod<[], undefined>,
  'deleteConfig' : ActorMethod<[bigint], undefined>,
  'deleteFAQ' : ActorMethod<[bigint], undefined>,
  'getAllChangelog' : ActorMethod<[], Array<Changelog>>,
  'getAllFAQs' : ActorMethod<[], Array<FAQ>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatbotConfig' : ActorMethod<[], [] | [ChatbotConfig]>,
  'getDownloadsByOS' : ActorMethod<[], DownloadStats>,
  'getLatestVersion' : ActorMethod<[], string>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMembershipStats' : ActorMethod<[], MembershipStats>,
  'getMyConfigs' : ActorMethod<[], Array<SavedConfig>>,
  'getMyLeaderboardRank' : ActorMethod<[], [] | [LeaderboardEntry]>,
  'getMyMembership' : ActorMethod<[], [] | [MembershipRecord]>,
  'getTopRewards' : ActorMethod<[], Array<TopReward>>,
  'getTotalConfigsCount' : ActorMethod<[], bigint>,
  'getTotalDownloads' : ActorMethod<[], bigint>,
  'getTotalMembersCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementDownload' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseMembership' : ActorMethod<[MembershipTier], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveChatbotConfig' : ActorMethod<[string, boolean], undefined>,
  'saveConfig' : ActorMethod<[string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];