/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClaimedReward = IDL.Record({
  'title' : IDL.Text,
  'rank' : IDL.Nat,
  'claimedAt' : IDL.Int,
  'badge' : IDL.Text,
  'bonusTokens' : IDL.Nat,
});
export const ForumPost = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'threadId' : IDL.Nat,
  'authorHandle' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
});
export const ForumThread = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'replyCount' : IDL.Nat,
  'lastActivityAt' : IDL.Int,
  'authorHandle' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
  'topicId' : IDL.Nat,
});
export const Changelog = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'changeType' : IDL.Text,
  'description' : IDL.Text,
  'version' : IDL.Text,
  'releaseDate' : IDL.Text,
  'changesList' : IDL.Vec(IDL.Text),
});
export const FAQ = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const ChatbotConfig = IDL.Record({
  'enabled' : IDL.Bool,
  'phoneNumber' : IDL.Text,
});
export const DownloadStats = IDL.Record({
  'windowsDownloads' : IDL.Nat,
  'macosDownloads' : IDL.Nat,
  'linuxDownloads' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
});
export const ForumTopic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const MembershipTier = IDL.Variant({
  'gold' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'joinedAt' : IDL.Int,
  'rank' : IDL.Nat,
  'tier' : MembershipTier,
  'tokens' : IDL.Nat,
  'handle' : IDL.Text,
});
export const MembershipStats = IDL.Record({
  'totalGold' : IDL.Nat,
  'totalSilver' : IDL.Nat,
  'totalPlatinum' : IDL.Nat,
  'totalMembers' : IDL.Nat,
});
export const SavedConfig = IDL.Record({
  'id' : IDL.Nat,
  'os' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'configData' : IDL.Text,
});
export const ForumNotification = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'threadTitle' : IDL.Text,
  'threadId' : IDL.Nat,
  'recipientPrincipal' : IDL.Principal,
  'fromHandle' : IDL.Text,
});
export const MembershipRecord = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'tier' : MembershipTier,
  'purchasedAt' : IDL.Int,
});
export const UserAccount = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'handle' : IDL.Text,
  'phone' : IDL.Text,
});
export const TopReward = IDL.Record({
  'title' : IDL.Text,
  'color' : IDL.Text,
  'rank' : IDL.Nat,
  'description' : IDL.Text,
  'badge' : IDL.Text,
  'bonusTokens' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [BlogPost],
      [],
    ),
  'addChangelog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'addFAQ' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimTopReward' : IDL.Func([IDL.Nat], [ClaimedReward], []),
  'createForumPost' : IDL.Func([IDL.Nat, IDL.Text], [ForumPost], []),
  'createForumThread' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [ForumThread],
      [],
    ),
  'deleteChangelog' : IDL.Func([IDL.Nat], [], []),
  'deleteChatbotConfig' : IDL.Func([], [], []),
  'deleteConfig' : IDL.Func([IDL.Nat], [], []),
  'deleteFAQ' : IDL.Func([IDL.Nat], [], []),
  'getAllChangelog' : IDL.Func([], [IDL.Vec(Changelog)], ['query']),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatbotConfig' : IDL.Func([], [IDL.Opt(ChatbotConfig)], ['query']),
  'getDownloadsByOS' : IDL.Func([], [DownloadStats], ['query']),
  'getForumPostsByThread' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ForumPost)],
      ['query'],
    ),
  'getForumThreadsByTopic' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ForumThread)],
      ['query'],
    ),
  'getForumTopics' : IDL.Func([], [IDL.Vec(ForumTopic)], ['query']),
  'getLatestVersion' : IDL.Func([], [IDL.Text], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMembershipStats' : IDL.Func([], [MembershipStats], ['query']),
  'getMyClaimedRewards' : IDL.Func([], [IDL.Vec(ClaimedReward)], ['query']),
  'getMyConfigs' : IDL.Func([], [IDL.Vec(SavedConfig)], ['query']),
  'getMyForumNotifications' : IDL.Func(
      [],
      [IDL.Vec(ForumNotification)],
      ['query'],
    ),
  'getMyLeaderboardRank' : IDL.Func([], [IDL.Opt(LeaderboardEntry)], ['query']),
  'getMyMembership' : IDL.Func([], [IDL.Opt(MembershipRecord)], ['query']),
  'getMyUserAccount' : IDL.Func([], [IDL.Opt(UserAccount)], ['query']),
  'getTopRewards' : IDL.Func([], [IDL.Vec(TopReward)], ['query']),
  'getTotalConfigsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalDownloads' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalMembersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserAccountByHandle' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserAccount)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasClaimedReward' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'incrementDownload' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markForumNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'purchaseMembership' : IDL.Func([MembershipTier], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveChatbotConfig' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'saveConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'saveUserAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClaimedReward = IDL.Record({
    'title' : IDL.Text,
    'rank' : IDL.Nat,
    'claimedAt' : IDL.Int,
    'badge' : IDL.Text,
    'bonusTokens' : IDL.Nat,
  });
  const ForumPost = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'threadId' : IDL.Nat,
    'authorHandle' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
  });
  const ForumThread = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'replyCount' : IDL.Nat,
    'lastActivityAt' : IDL.Int,
    'authorHandle' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
    'topicId' : IDL.Nat,
  });
  const Changelog = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'changeType' : IDL.Text,
    'description' : IDL.Text,
    'version' : IDL.Text,
    'releaseDate' : IDL.Text,
    'changesList' : IDL.Vec(IDL.Text),
  });
  const FAQ = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const ChatbotConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'phoneNumber' : IDL.Text,
  });
  const DownloadStats = IDL.Record({
    'windowsDownloads' : IDL.Nat,
    'macosDownloads' : IDL.Nat,
    'linuxDownloads' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
  });
  const ForumTopic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const MembershipTier = IDL.Variant({
    'gold' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'joinedAt' : IDL.Int,
    'rank' : IDL.Nat,
    'tier' : MembershipTier,
    'tokens' : IDL.Nat,
    'handle' : IDL.Text,
  });
  const MembershipStats = IDL.Record({
    'totalGold' : IDL.Nat,
    'totalSilver' : IDL.Nat,
    'totalPlatinum' : IDL.Nat,
    'totalMembers' : IDL.Nat,
  });
  const SavedConfig = IDL.Record({
    'id' : IDL.Nat,
    'os' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'configData' : IDL.Text,
  });
  const ForumNotification = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'threadTitle' : IDL.Text,
    'threadId' : IDL.Nat,
    'recipientPrincipal' : IDL.Principal,
    'fromHandle' : IDL.Text,
  });
  const MembershipRecord = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'tier' : MembershipTier,
    'purchasedAt' : IDL.Int,
  });
  const UserAccount = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'handle' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TopReward = IDL.Record({
    'title' : IDL.Text,
    'color' : IDL.Text,
    'rank' : IDL.Nat,
    'description' : IDL.Text,
    'badge' : IDL.Text,
    'bonusTokens' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [BlogPost],
        [],
      ),
    'addChangelog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'addFAQ' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimTopReward' : IDL.Func([IDL.Nat], [ClaimedReward], []),
    'createForumPost' : IDL.Func([IDL.Nat, IDL.Text], [ForumPost], []),
    'createForumThread' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [ForumThread],
        [],
      ),
    'deleteChangelog' : IDL.Func([IDL.Nat], [], []),
    'deleteChatbotConfig' : IDL.Func([], [], []),
    'deleteConfig' : IDL.Func([IDL.Nat], [], []),
    'deleteFAQ' : IDL.Func([IDL.Nat], [], []),
    'getAllChangelog' : IDL.Func([], [IDL.Vec(Changelog)], ['query']),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatbotConfig' : IDL.Func([], [IDL.Opt(ChatbotConfig)], ['query']),
    'getDownloadsByOS' : IDL.Func([], [DownloadStats], ['query']),
    'getForumPostsByThread' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ForumPost)],
        ['query'],
      ),
    'getForumThreadsByTopic' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ForumThread)],
        ['query'],
      ),
    'getForumTopics' : IDL.Func([], [IDL.Vec(ForumTopic)], ['query']),
    'getLatestVersion' : IDL.Func([], [IDL.Text], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMembershipStats' : IDL.Func([], [MembershipStats], ['query']),
    'getMyClaimedRewards' : IDL.Func([], [IDL.Vec(ClaimedReward)], ['query']),
    'getMyConfigs' : IDL.Func([], [IDL.Vec(SavedConfig)], ['query']),
    'getMyForumNotifications' : IDL.Func(
        [],
        [IDL.Vec(ForumNotification)],
        ['query'],
      ),
    'getMyLeaderboardRank' : IDL.Func(
        [],
        [IDL.Opt(LeaderboardEntry)],
        ['query'],
      ),
    'getMyMembership' : IDL.Func([], [IDL.Opt(MembershipRecord)], ['query']),
    'getMyUserAccount' : IDL.Func([], [IDL.Opt(UserAccount)], ['query']),
    'getTopRewards' : IDL.Func([], [IDL.Vec(TopReward)], ['query']),
    'getTotalConfigsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalDownloads' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalMembersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserAccountByHandle' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserAccount)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasClaimedReward' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'incrementDownload' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markForumNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'purchaseMembership' : IDL.Func([MembershipTier], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveChatbotConfig' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'saveConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'saveUserAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };