/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    principal: Principal;
    displayName: string;
    joinedAt: bigint;
    rank: bigint;
    tier: MembershipTier;
    tokens: bigint;
    handle: string;
}
export interface FAQ {
    id: bigint;
    question: string;
    answer: string;
    category: string;
}
export interface MembershipRecord {
    id: bigint;
    owner: Principal;
    tier: MembershipTier;
    purchasedAt: bigint;
}
export interface TopReward {
    title: string;
    color: string;
    rank: bigint;
    description: string;
    badge: string;
    bonusTokens: bigint;
}
export interface ClaimedReward {
    title: string;
    rank: bigint;
    claimedAt: bigint;
    badge: string;
    bonusTokens: bigint;
}
export interface ChatbotConfig {
    enabled: boolean;
    phoneNumber: string;
}
export interface DownloadStats {
    windowsDownloads: bigint;
    macosDownloads: bigint;
    linuxDownloads: bigint;
    totalDownloads: bigint;
}
export interface SavedConfig {
    id: bigint;
    os: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    configData: string;
}
export interface MembershipStats {
    totalGold: bigint;
    totalSilver: bigint;
    totalPlatinum: bigint;
    totalMembers: bigint;
}
export interface UserProfile {
    bio?: string;
    name: string;
}
export interface Changelog {
    id: bigint;
    title: string;
    changeType: string;
    description: string;
    version: string;
    releaseDate: string;
    changesList: Array<string>;
}
export enum MembershipTier {
    gold = "gold",
    platinum = "platinum",
    silver = "silver"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChangelog(version: string, releaseDate: string, title: string, description: string, changesList: Array<string>, changeType: string): Promise<void>;
    addFAQ(question: string, answer: string, category: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimTopReward(rank: bigint): Promise<ClaimedReward>;
    deleteChangelog(id: bigint): Promise<void>;
    deleteChatbotConfig(): Promise<void>;
    deleteConfig(id: bigint): Promise<void>;
    deleteFAQ(id: bigint): Promise<void>;
    getAllChangelog(): Promise<Array<Changelog>>;
    getAllFAQs(): Promise<Array<FAQ>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatbotConfig(): Promise<ChatbotConfig | null>;
    getDownloadsByOS(): Promise<DownloadStats>;
    getLatestVersion(): Promise<string>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMembershipStats(): Promise<MembershipStats>;
    getMyClaimedRewards(): Promise<Array<ClaimedReward>>;
    getMyConfigs(): Promise<Array<SavedConfig>>;
    getMyLeaderboardRank(): Promise<LeaderboardEntry | null>;
    getMyMembership(): Promise<MembershipRecord | null>;
    getTopRewards(): Promise<Array<TopReward>>;
    getTotalConfigsCount(): Promise<bigint>;
    getTotalDownloads(): Promise<bigint>;
    getTotalMembersCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasClaimedReward(rank: bigint): Promise<boolean>;
    incrementDownload(os: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    purchaseMembership(tier: MembershipTier): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveChatbotConfig(phoneNumber: string, enabled: boolean): Promise<void>;
    saveConfig(name: string, os: string, configData: string): Promise<bigint>;
}
import type { ChatbotConfig as _ChatbotConfig, LeaderboardEntry as _LeaderboardEntry, MembershipRecord as _MembershipRecord, MembershipTier as _MembershipTier, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChangelog(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChangelog(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChangelog(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addFAQ(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQ(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQ(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimTopReward(arg0: bigint): Promise<ClaimedReward> {
        if (this.processError) {
            try {
                const result = await this.actor.claimTopReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimTopReward(arg0);
            return result;
        }
    }
    async deleteChangelog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChangelog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChangelog(arg0);
            return result;
        }
    }
    async deleteChatbotConfig(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatbotConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatbotConfig();
            return result;
        }
    }
    async deleteConfig(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConfig(arg0);
            return result;
        }
    }
    async deleteFAQ(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFAQ(arg0);
            return result;
        }
    }
    async getAllChangelog(): Promise<Array<Changelog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChangelog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChangelog();
            return result;
        }
    }
    async getAllFAQs(): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFAQs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatbotConfig(): Promise<ChatbotConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatbotConfig();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatbotConfig();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDownloadsByOS(): Promise<DownloadStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDownloadsByOS();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDownloadsByOS();
            return result;
        }
    }
    async getLatestVersion(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestVersion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestVersion();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipStats(): Promise<MembershipStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipStats();
            return result;
        }
    }
    async getMyClaimedRewards(): Promise<Array<ClaimedReward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyClaimedRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyClaimedRewards();
            return result;
        }
    }
    async getMyConfigs(): Promise<Array<SavedConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConfigs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConfigs();
            return result;
        }
    }
    async getMyLeaderboardRank(): Promise<LeaderboardEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLeaderboardRank();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLeaderboardRank();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMembership(): Promise<MembershipRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMembership();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMembership();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopRewards(): Promise<Array<TopReward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopRewards();
            return result;
        }
    }
    async getTotalConfigsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalConfigsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalConfigsCount();
            return result;
        }
    }
    async getTotalDownloads(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalDownloads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalDownloads();
            return result;
        }
    }
    async getTotalMembersCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalMembersCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalMembersCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasClaimedReward(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasClaimedReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasClaimedReward(arg0);
            return result;
        }
    }
    async incrementDownload(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementDownload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementDownload(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async purchaseMembership(arg0: MembershipTier): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseMembership(to_candid_MembershipTier_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseMembership(to_candid_MembershipTier_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveChatbotConfig(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveChatbotConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveChatbotConfig(arg0, arg1);
            return result;
        }
    }
    async saveConfig(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveConfig(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveConfig(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_LeaderboardEntry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipRecord): MembershipRecord {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipTier_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipTier): MembershipTier {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeaderboardEntry]): LeaderboardEntry | null {
    return value.length === 0 ? null : from_candid_LeaderboardEntry_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MembershipRecord]): MembershipRecord | null {
    return value.length === 0 ? null : from_candid_MembershipRecord_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatbotConfig]): ChatbotConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    displayName: string;
    joinedAt: bigint;
    rank: bigint;
    tier: _MembershipTier;
    tokens: bigint;
    handle: string;
}): {
    principal: Principal;
    displayName: string;
    joinedAt: bigint;
    rank: bigint;
    tier: MembershipTier;
    tokens: bigint;
    handle: string;
} {
    return {
        principal: value.principal,
        displayName: value.displayName,
        joinedAt: value.joinedAt,
        rank: value.rank,
        tier: from_candid_MembershipTier_n13(_uploadFile, _downloadFile, value.tier),
        tokens: value.tokens,
        handle: value.handle
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: Principal;
    tier: _MembershipTier;
    purchasedAt: bigint;
}): {
    id: bigint;
    owner: Principal;
    tier: MembershipTier;
    purchasedAt: bigint;
} {
    return {
        id: value.id,
        owner: value.owner,
        tier: from_candid_MembershipTier_n13(_uploadFile, _downloadFile, value.tier),
        purchasedAt: value.purchasedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    name: string;
}): {
    bio?: string;
    name: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.bio)),
        name: value.name
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gold: null;
} | {
    platinum: null;
} | {
    silver: null;
}): MembershipTier {
    return "gold" in value ? MembershipTier.gold : "platinum" in value ? MembershipTier.platinum : "silver" in value ? MembershipTier.silver : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n11(_uploadFile, _downloadFile, x));
}
function to_candid_MembershipTier_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): _MembershipTier {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    name: string;
}): {
    bio: [] | [string];
    name: string;
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): {
    gold: null;
} | {
    platinum: null;
} | {
    silver: null;
} {
    return value == MembershipTier.gold ? {
        gold: null
    } : value == MembershipTier.platinum ? {
        platinum: null
    } : value == MembershipTier.silver ? {
        silver: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
